nome=str(input())
idade=int(input())
altura=float(input())
peso=float(input())
nacionalidade=str(input())

print(nome)
print(idade,"anos")
print("%.2f"%altura,"de altura")
print("%.2f"%peso,"quilos")
print(nacionalidade)
